-- 45:45 product core: matches, players, news approval, chants, community, predictions, attendance, moderation.
create type public.content_status as enum ('pending','approved','published','rejected','archived');
create type public.match_status as enum ('scheduled','live','finished','postponed','cancelled');
create table public.matches(id uuid primary key default gen_random_uuid(),competition text not null,round_name text,home_club_id uuid references public.clubs,away_club_id uuid references public.clubs,home_name text,away_name text,kickoff timestamptz not null,stadium text,status public.match_status not null default 'scheduled',home_score int,away_score int,provider_id text unique,created_at timestamptz default now());
create table public.match_events(id bigint generated always as identity primary key,match_id uuid references public.matches on delete cascade,minute int,event_type text not null,club_id uuid references public.clubs,player_name text,detail text,created_at timestamptz default now());
create table public.players(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs on delete cascade,name text not null,number int,position text,nationality text,birth_date date,image_url text,active boolean default true,created_at timestamptz default now());
create table public.player_season_stats(id uuid primary key default gen_random_uuid(),player_id uuid references public.players on delete cascade,season text not null,appearances int default 0,goals int default 0,assists int default 0,minutes int default 0,unique(player_id,season));
create table public.news_items(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs,title text not null,summary text,source_name text,source_url text,category text,image_url text,official boolean default false,status public.content_status not null default 'pending',ai_group_key text,created_by uuid references public.profiles,approved_by uuid references public.profiles,published_at timestamptz,created_at timestamptz default now());
create table public.chants(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs on delete cascade,line text not null,enabled boolean default true,sort_order int default 0,created_by uuid references public.profiles,created_at timestamptz default now());
create table public.widget_schedule(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs on delete cascade,slot_time time not null,chant_id uuid references public.chants on delete cascade,override_date date,enabled boolean default true);
create table public.polls(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs,question text not null,options jsonb not null,status public.content_status default 'pending',closes_at timestamptz,created_at timestamptz default now());
create table public.poll_votes(poll_id uuid references public.polls on delete cascade,user_id uuid references public.profiles on delete cascade,option_index int not null,created_at timestamptz default now(),primary key(poll_id,user_id));
create table public.predictions(match_id uuid references public.matches on delete cascade,user_id uuid references public.profiles on delete cascade,home_score int not null,away_score int not null,created_at timestamptz default now(),primary key(match_id,user_id));
create table public.match_attendance(match_id uuid references public.matches on delete cascade,user_id uuid references public.profiles on delete cascade,created_at timestamptz default now(),primary key(match_id,user_id));
create table public.community_posts(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs on delete cascade,author_id uuid references public.profiles on delete cascade,body text not null,removed_at timestamptz,created_at timestamptz default now());
create table public.chat_messages(id bigint generated always as identity primary key,club_id uuid references public.clubs,match_id uuid references public.matches,author_id uuid references public.profiles on delete cascade,body text not null,reply_to bigint references public.chat_messages,removed_at timestamptz,created_at timestamptz default now(),check(club_id is not null or match_id is not null));
create table public.moderation_cases(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles,club_id uuid references public.clubs,match_id uuid references public.matches,message_id bigint references public.chat_messages,reason text not null,ai_confidence numeric,status text not null default 'open',temporary_lock_until timestamptz,moderator_id uuid references public.profiles,moderator_note text,created_at timestamptz default now(),resolved_at timestamptz);
create table public.club_history(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs on delete cascade,event_date date,title text not null,body text,image_url text,created_at timestamptz default now());

alter table public.matches enable row level security; alter table public.players enable row level security; alter table public.player_season_stats enable row level security; alter table public.news_items enable row level security; alter table public.chants enable row level security; alter table public.polls enable row level security; alter table public.community_posts enable row level security; alter table public.chat_messages enable row level security;
create policy "matches public read" on public.matches for select using (true); create policy "players public read" on public.players for select using (active=true); create policy "stats public read" on public.player_season_stats for select using (true); create policy "published news read" on public.news_items for select using(status='published'); create policy "chants read" on public.chants for select using(enabled=true); create policy "published polls read" on public.polls for select using(status='published'); create policy "posts read" on public.community_posts for select using(removed_at is null); create policy "chat read" on public.chat_messages for select using(removed_at is null);
create index matches_kickoff_idx on public.matches(kickoff); create index news_club_published_idx on public.news_items(club_id,published_at desc); create index chat_club_created_idx on public.chat_messages(club_id,created_at desc); create index chat_match_created_idx on public.chat_messages(match_id,created_at desc);
